path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos/videos
  
  output: exported_models/eval
  
  working: work_dir/octo-1

  model: exported_models/DLC_Tent6_mobilenet_v2_0.35_iteration-0_shuffle-1

info:
  fps: 30