path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos/videos
  
  output: exported_models/eval
  
  working: work_dir/octo-1

  model: exported_models/octopus_Tent6_mobilenet_keypoint5

info:
  fps: 30