path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos1/videos
  
  xls: OctopusVideos1/Movement_class_and_timestamps_end_stim.xlsx
  
  working: work_dir/octo-1

  model: exported_models/DLC_Tent6_mobilenet_v2_0.35_iteration-0_shuffle-1
  # resnet -> /DLC_Tent6_resnet_50_iteration-0_shuffle-1

info:
  fps: 30