path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos2/December_experiments
  
  xls: OctopusVideos2/December_experiments/December_Movement_class_and_timestamps.xlsx
  
  working: work_dir/octo-2

  model: exported_models/DLC_Tent6_mobilenet_v2_0.35_iteration-0_shuffle-1

info:
  fps: 30