path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos2/Large_Videos_tmp
  
  xls: 
  
  working: work_dir/octo-2-large

  model: exported_models/DLC_Tent6_mobilenet_v2_0.35_iteration-0_shuffle-1

info:
  fps: 30