path:
  root: /home/sachinks/Code/MyProjects
  
  video: OctopusVideos/videos
  
  xls: /nfs/turbo/umms-adraelos/sachinks/stim_behavior/metadata.xlsx
  
  working: work_dir/octo-17

  model: exported_models/DLC_Octo-Arm_resnet_50_iteration-0_shuffle-1-keypoint17

info:
  fps: 30