path:
  root: /home/sachinks/Code/MyProjects
  
  video: /home/sachinks/Code/stim_behavior/data/video
  
  xls:
  
  working: work_dir/zebrafish

  model: exported_models/DLC_Tent6_mobilenet_v2_0.35_iteration-0_shuffle-1

info:
  fps: 30